# The model, and nothing that draws it.
#
# Every file under `src/roguelike/` that is part of the model requires this
# file, and this file requires every one of them. A file is then whole on its
# own, and the order they are listed in below is the only order there is.
# Requiring one file and finding a type it uses undefined is what this is for.
#
# The terminal is not in here. `src/crystal-roguelike.cr` requires this and
# then the parts that draw a run, which are the only parts that need termbuf.
# A program that requires only this file compiles against the model alone,
# and the binary it builds links no terminal library.
require "./roguelike/version"
require "./roguelike/rng"
require "./roguelike/direction"
require "./roguelike/line"
require "./roguelike/pace"
require "./roguelike/regard"
require "./roguelike/costs"
require "./roguelike/attributes"
require "./roguelike/advancement"
require "./roguelike/terrain"
require "./roguelike/tile"
require "./roguelike/species"
require "./roguelike/monster"
require "./roguelike/notice"
require "./roguelike/fixture"
require "./roguelike/floor"
require "./roguelike/field_of_view"
require "./roguelike/apply"
require "./roguelike/lighting"
require "./roguelike/vision"
require "./roguelike/knowledge"
require "./roguelike/descent"
require "./roguelike/pursuit"
require "./roguelike/route"
require "./roguelike/floors"
require "./roguelike/dice"
require "./roguelike/combat"
require "./roguelike/effect"
require "./roguelike/item_kind"
require "./roguelike/handling"
require "./roguelike/item"
require "./roguelike/items"
require "./roguelike/loot"
require "./roguelike/spawns"
require "./roguelike/audit"
require "./roguelike/inventory"
require "./roguelike/slot"
require "./roguelike/equipment"
require "./roguelike/lore"
require "./roguelike/message_log"
require "./roguelike/world"
require "./roguelike/action"
require "./roguelike/event"
require "./roguelike/running"
require "./roguelike/flight"
require "./roguelike/generator"
require "./roguelike/fingerprint"
require "./roguelike/player"
require "./roguelike/game"
require "./roguelike/observation"
require "./roguelike/save"
require "./roguelike/replay"
require "./roguelike/names"
require "./roguelike/trial"
require "./roguelike/trial/matchup"
require "./roguelike/debug/naming"
require "./roguelike/debug/console"
